name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
      
    - name: Run tests
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      
    - name: Test Examples project can run
      if: matrix.os == 'ubuntu-latest' && matrix.configuration == 'Release'
      run: |
        echo "Testing that Examples project can execute basic scenarios..."
        cd Examples
        timeout 30s dotnet run hello || true
        echo "Examples project smoke test completed"

  package-validation:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build AzureAdapter package
      run: |
        dotnet build src/Asynkron.DurableFunctions.AzureAdapter --configuration Release
        dotnet pack src/Asynkron.DurableFunctions.AzureAdapter --configuration Release --no-build --output ./packages
        
    - name: Upload NuGet packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: packages/*.nupkg
        retention-days: 7